version: '2'

services:
  order_app:
    image: 'order-service:latest'
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: order_app

    depends_on:
      - order_db
    env_file:
      - .env
    ports:
      - "8081:8080"
      - "5006:5005"


  order_db:
    image: 'postgres:13.1-alpine'
    container_name: order_db
    env_file:
      - .env
    volumes:
      - ../src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - order-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  order-db-data: